All in one
a1yak/AndroidHomework pull request #6
Opened 2022-05-25 23:20 UTC by a1yak

Homework Fragments

2022-05-26 16:42 UTC, a1yak commented
тут сразу фрагменты+логин

2022-05-30 07:22 UTC, OKurcheuskaya commented
коммиты должны быть описательными, названиz "o, n" не допустимы

2022-05-30 07:32 UTC, OKurcheuskaya requested changes

2022-05-30 07:32 UTC, OKurcheuskaya commented on AllinOne/app/src/main/java/com/example/fragments/FragmentLogin.kt
> +                Toast.makeText(context,"Incorrect password or login, try again",Toast.LENGTH_SHORT).show()
через when обработай логику, когда ничего не введено

2022-05-30 07:32 UTC, OKurcheuskaya commented on AllinOne/app/src/main/java/com/example/fragments/FragmentLogin.kt
> +                    ?.replace(R.id.placeForFragments, frg_default)?.commit()
передай логин и пароль дефолтному фрагменту

2022-06-06 07:48 UTC, OKurcheuskaya approved these changes
пожалуйста, проверяй какие файлы ты включаешь в коммит! не  должно быть .idea and .gradle

2022-06-06 07:58 UTC, merged